// aiEdit 裸替换指令 + 删除标点清理 测试
const path = require('path')
const base = path.join(__dirname, '..')
const aiEdit = require(path.join(base, 'utils', 'aiEdit.js'))

let pass = 0, fail = 0
function check(name, actual, expected) {
  const ok = actual === expected
  if (ok) { pass++; console.log('  ✓ ' + name) }
  else { fail++; console.log('  ✗ ' + name + '\n      期望: ' + JSON.stringify(expected) + '\n      实际: ' + JSON.stringify(actual)) }
}

console.log('== 1. 裸替换指令识别（detect）==')
let d = aiEdit.detect('北京改为北京朝阳区')
check('北京改为北京朝阳区 → replace', d && d.type === 'replace' && d.from === '北京' && d.to === '北京朝阳区', true)
d = aiEdit.detect('北京改成北京朝阳区')
check('北京改成北京朝阳区 → replace', d && d.type === 'replace' && d.from === '北京' && d.to === '北京朝阳区', true)
d = aiEdit.detect('名字换成小明')
check('X换成Y → replace', d && d.type === 'replace' && d.from === '名字' && d.to === '小明', true)
d = aiEdit.detect('公司名称更改为腾讯', )
check('X更改为Y → replace', d && d.type === 'replace' && d.from === '公司名称' && d.to === '腾讯', true)
d = aiEdit.detect('北京改为北京朝阳区', { loose: true })
check('语音宽松模式也识别裸替换', d && d.type === 'replace' && d.from === '北京', true)

console.log('== 2. 误判防护（普通叙述不识别）==')
d = aiEdit.detect('他改成了学霸')
check('X 单字不识别（他改成了学霸）', d === null, true)
d = aiEdit.detect('不只是朋友是兄弟')
check('叙述句不识别（不只是朋友是兄弟）', d === null, true)
d = aiEdit.detect('我计划改为周日去爬山，今天先休息')
check('含逗号长句不识别', d === null, true)

console.log('== 3. apply 裸替换执行 ==')
let r = aiEdit.apply('小李今天去北京上大学了', { type: 'replace', from: '北京', to: '北京朝阳区' })
check('用户例1：北京→北京朝阳区', r.content, '小李今天去北京朝阳区上大学了')
r = aiEdit.apply('今天天气很好', { type: 'replace', from: '北京', to: '北京朝阳区' })
check('找不到目标词 → notFound', r.reason, 'notFound')

console.log('== 4. 删除 + 悬空标点清理 ==')
r = aiEdit.apply('今天是个大晴天，万里无云，暖风习习。', { type: 'remove', from: '暖风习习' })
check('用户例2：去掉暖风习习（句尾）', r.content, '今天是个大晴天，万里无云。')
r = aiEdit.apply('今天，暖风习习，天气很好', { type: 'remove', from: '暖风习习' })
check('句中删除合并分隔符', r.content, '今天，天气很好')
r = aiEdit.apply('暖风习习，万里无云', { type: 'remove', from: '暖风习习' })
check('句首删除去行首分隔符', r.content, '万里无云')
r = aiEdit.apply('今天是个大晴天，万里无云，暖风习习', { type: 'remove', from: '暖风习习' })
check('删除后整段末尾悬空逗号', r.content, '今天是个大晴天，万里无云')
// 用户反馈：语音识别带句号导致目标词被吃进标点
r = aiEdit.apply('需要跟进处理。整个过程中，心情保持平淡而平静。', aiEdit.detect('去掉整个过程中。', { loose: true }))
check('语音识别带句号的目标词也能正确删除并清理句后逗号', r.content, '需要跟进处理。心情保持平淡而平静。')

console.log('== 5. AI优化场景：extractEmbedded（指令句不保留）==')
let e = aiEdit.extractEmbedded('小李今天去北京上大学了。北京改为北京朝阳区。')
check('例1 全文：指令执行且不保留', e.content, '小李今天去北京朝阳区上大学了。')
e = aiEdit.extractEmbedded('今天是个大晴天，万里无云，暖风习习。去掉暖风习习。')
check('例2 全文：指令执行且不保留', e.content, '今天是个大晴天，万里无云。')
e = aiEdit.extractEmbedded('今天天气很好。心情改为开心。')
check('找不到目标词的指令按叙述保留', e.content, '今天天气很好。心情改为开心。')
e = aiEdit.extractEmbedded('今天天气很好。')
check('纯叙述不受影响', e.content, '今天天气很好。')

console.log('== 6. 回归：既有指令模式 ==')
d = aiEdit.detect('不是王磊，是王伟')
check('不是X，是Y 仍识别', d && d.type === 'replace' && d.from === '王磊' && d.to === '王伟', true)
d = aiEdit.detect('把开心删掉')
check('把X删掉 仍识别', d && d.type === 'remove' && d.from === '开心', true)
d = aiEdit.detect('去掉暖风习习')
check('去掉X 仍识别', d && d.type === 'remove' && d.from === '暖风习习', true)
d = aiEdit.detect('在大学前边加上北京')
check('插入指令仍识别', d && d.type === 'insert' && d.at === '大学' && d.text === '北京', true)
d = aiEdit.detect('不是王磊是王伟', { loose: true })
check('语音宽松 不是X是Y 仍识别', d && d.type === 'replace' && d.from === '王磊', true)
const p = aiEdit.splitCommands('王伟来找我。把开心删掉。今天很充实。')
check('splitCommands 混合拆分：指令1条', p.commands.length, 1)
check('splitCommands 混合拆分：叙述保留', p.narrative.indexOf('王伟来找我') !== -1 && p.narrative.indexOf('充实') !== -1, true)
e = aiEdit.extractEmbedded('王伟来找我。不是王伟，是王维。')
check('extractEmbedded 既有路径仍工作', e.content, '王维来找我。')

console.log('== 7. 量词剥离（把文中所有X变成Y）==')
d = aiEdit.detect('把文中所有小王变成老王')
check('把文中所有小王变成老王 → replace 小王→老王', d && d.type === 'replace' && d.from === '小王' && d.to === '老王', true)
d = aiEdit.detect('所有小王都变成老王')
check('所有小王都变成老王 → replace 小王→老王', d && d.type === 'replace' && d.from === '小王' && d.to === '老王', true)
d = aiEdit.detect('删除文中所有小王')
check('删除文中所有小王 → remove 小王', d && d.type === 'remove' && d.from === '小王', true)
d = aiEdit.detect('成都改为重庆')
check('「成都」不被量词后缀误剥', d && d.from === '成都' && d.to === '重庆', true)
r = aiEdit.apply('小王去找小王借书，小王说没有', { type: 'replace', from: '小王', to: '老王' })
check('全局替换所有小王', r.content, '老王去找老王借书，老王说没有')
check('全局替换计数 count=3', r.count, 3)

console.log('== 8. 按位置删句（detect）==')
d = aiEdit.detect('删除最后一句话')
check('删除最后一句话 → last/1', d && d.type === 'removeSent' && d.pos === 'last' && d.count === 1, true)
d = aiEdit.detect('去掉第一句')
check('去掉第一句 → first/1', d && d.type === 'removeSent' && d.pos === 'first' && d.count === 1, true)
d = aiEdit.detect('把最后一句话删掉')
check('把最后一句话删掉 → last/1', d && d.type === 'removeSent' && d.pos === 'last', true)
d = aiEdit.detect('删除第一句话')
check('删除第一句话 → first/1', d && d.type === 'removeSent' && d.pos === 'first', true)
d = aiEdit.detect('删掉结尾两句')
check('删掉结尾两句 → last/2', d && d.type === 'removeSent' && d.pos === 'last' && d.count === 2, true)
d = aiEdit.detect('删除倒数第二句')
check('删除倒数第二句 → last/offset1', d && d.type === 'removeSent' && d.pos === 'last' && d.offset === 1 && d.count === 1, true)
d = aiEdit.detect('删除开头一句')
check('删除开头一句 → first/1', d && d.type === 'removeSent' && d.pos === 'first' && d.count === 1, true)
d = aiEdit.detect('第一句话很难忘')
check('叙述句「第一句话很难忘」不识别', d === null, true)

console.log('== 9. 按位置删句（apply）==')
const S4 = '今天天气很好。小王去了北京。心情不错。晚上吃了火锅。'
r = aiEdit.apply(S4, { type: 'removeSent', pos: 'last', count: 1, offset: 0 })
check('删最后一句', r.content, '今天天气很好。小王去了北京。心情不错。')
r = aiEdit.apply(S4, { type: 'removeSent', pos: 'first', count: 1, offset: 0 })
check('删第一句', r.content, '小王去了北京。心情不错。晚上吃了火锅。')
r = aiEdit.apply(S4, { type: 'removeSent', pos: 'last', count: 2, offset: 0 })
check('删最后两句', r.content, '今天天气很好。小王去了北京。')
r = aiEdit.apply(S4, { type: 'removeSent', pos: 'last', count: 1, offset: 1 })
check('删倒数第二句（保留最后一句）', r.content, '今天天气很好。小王去了北京。晚上吃了火锅。')
r = aiEdit.apply('只有一句话', { type: 'removeSent', pos: 'last', count: 1, offset: 0 })
check('单句删除后为空', r.content, '')

console.log('== 10. AI优化场景全链路（extractEmbedded）==')
e = aiEdit.extractEmbedded('今天小王很开心。小王去了北京。小王说北京很大。把文中所有小王变成老王。')
check('全局替换全链路：所有小王→老王', e.content, '今天老王很开心。老王去了北京。老王说北京很大。')
e = aiEdit.extractEmbedded('第一句写这里。第二句也写了。第三句收尾。删除最后一句话。')
check('删最后一句全链路', e.content, '第一句写这里。第二句也写了。')
e = aiEdit.extractEmbedded('第一句写这里。第二句也写了。第三句收尾。删除第一句话。')
check('删第一句全链路', e.content, '第二句也写了。第三句收尾。')

console.log('\n===== 结果: pass ' + pass + ' fail ' + fail + ' =====')
process.exit(fail > 0 ? 1 : 0)
